// V4: integrate shelters, escorts, tactical map and mission priority into the main loop.
function animate(){
  if(!game?.running)return;const dt=Math.min(clock.getDelta(),.034);
  if(!game.paused&&!game.mapOpen){
    game.time+=dt;game.hudAcc+=dt;game.mapAcc+=dt;updatePlayer(dt);updateVehicles(dt);updateSoldiers(dt);updateCivilians(dt);updateFacilities(dt);updateShelters(dt);updateEvacConvoys(dt);updateZombies(dt);updateEffects(dt);spawnZombies(dt);updateRegen(dt);updateCityEvents(dt);updateCityMood(dt);updateExploration();
    if(game.hudAcc>.12){updateHUD();game.hudAcc=0;}if(game.mapAcc>.22){drawTacticalMap(false);game.mapAcc=0;}
  }else if(game.mapOpen){drawTacticalMap(true);}
  updateCamera(dt);renderer.render(scene,camera);raf=requestAnimationFrame(animate);
}
function updateHUD(){if(!game)return;
  els.civilianStat.textContent=`${game.carried} / ${game.evacuated}`;els.squadStat.textContent=`${game.soldiers.length} / ${game.squadMax}`;els.armorStat.textContent=String(1+game.vehicles.length);els.supplyStat.textContent=`K ${game.kills} · DROP ${Math.max(0,game.nextDropKills-game.kills)}`;els.formationStat.textContent=game.formation==='column'?'COLUMN':'WIDE';els.formationStat.style.color=game.formation==='column'?'var(--mint)':'var(--ice)';
  const threat=game.activeFacility?Math.min(5,2+game.facilitiesDone):Math.min(5,1+Math.floor(game.time/60));game.threat=Math.max(game.threat,threat);els.threatLabel.textContent=String(game.threat);els.threatBar.style.width=`${game.threat*20}%`;
  if(game.activeFacility){const f=game.activeFacility,t=Math.max(0,game.defenseRemaining);els.missionText.textContent=`${f.type} GARRISON · SAFE`;els.objectiveTitle.textContent=`${f.name} 주둔 방어`;els.objectiveDesc.textContent='분대는 건물 내부에서 보호받으며 강화 사격 중입니다.';els.objectiveTimer.textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.ceil(t%60)).padStart(2,'0')}`;els.objectiveTimer.classList.remove('hidden');return;}
  const escort=(game.evacConvoys||[]).find(c=>!c.done&&(c.state==='moving'||c.state==='loading'));if(escort){const hp=Math.max(0,Math.round(escort.hp/escort.maxHp*100));els.missionText.textContent=`EVAC ESCORT · ${escort.passengers} CIVILIANS`;els.objectiveTitle.textContent=`${escort.type==='bus'?'대피 버스':'수송 트럭'} 호위`;els.objectiveDesc.textContent=`차량 내구도 ${hp}% · 탑승 ${escort.passengers}명 · 도시 외곽까지 호위하십시오.`;if(escort.state==='loading'){els.objectiveTimer.textContent=`LOAD ${Math.max(0,Math.ceil(escort.load))}s`;els.objectiveTimer.classList.remove('hidden');}else els.objectiveTimer.classList.add('hidden');return;}
  const timed=(game.cityEvents||[]).find(e=>!e.done&&e.phase==='defend');if(timed){els.missionText.textContent=`RESCUE · ${timed.label}`;els.objectiveTitle.textContent=timed.label;els.objectiveDesc.textContent=timed.type==='rooftop'?'헬기 착륙이 완료될 때까지 주변 감염체를 저지하십시오.':'건물 출입구를 지키며 생존자 이탈을 엄호하십시오.';els.objectiveTimer.textContent=`00:${String(Math.max(0,Math.ceil(timed.timer))).padStart(2,'0')}`;els.objectiveTimer.classList.remove('hidden');return;}
  const urgent=(game.cityEvents||[]).find(e=>!e.done&&e.type!=='breach'&&e.phase==='waiting');if(urgent){const left=Math.max(0,urgent.expires-game.time);els.missionText.textContent=`URGENT · ${urgent.label}`;els.objectiveTitle.textContent=urgent.label;els.objectiveDesc.textContent='TAB 작전지도에서 신호 위치를 확인하고 제한 시간 안에 접근하십시오.';els.objectiveTimer.textContent=`00:${String(Math.ceil(left)).padStart(2,'0')}`;els.objectiveTimer.classList.remove('hidden');return;}
  const shelter=game.shelters.find(s=>s.discovered&&s.state==='idle');if(shelter){els.missionText.textContent=`SHELTER · ${shelter.people} CIVILIANS`;els.objectiveTitle.textContent=`${shelter.name} 확보`;els.objectiveDesc.textContent=`쉘터 접근 후 안전을 확보하면 ${shelter.method==='bus'?'버스':'트럭'} 대피 작전이 시작됩니다.`;els.objectiveTimer.classList.add('hidden');return;}
  const next=game.facilities.find(f=>f.state==='idle');els.missionText.textContent=`EVAC ${game.evacuated} · LOST ${game.lostCivilians||0} · INFECTED ${game.zombies.length}`;els.objectiveTitle.textContent=next?`${next.type} 확보`:'도시 구조작전 지속';els.objectiveDesc.textContent=next?'주요시설을 확보하거나 지도상의 쉘터·긴급신호를 선택하십시오.':'도시의 남은 구조 요청과 쉘터 대피를 계속 수행하십시오.';els.objectiveTimer.classList.add('hidden');
}
function finishGame(){
  if(!game?.running)return;game.running=false;cancelAnimationFrame(raf);if(v4MiniCanvas)v4MiniCanvas.style.display='none';if(v4MapWrap)v4MapWrap.classList.remove('visible');const total=game.evacuated,lost=game.lostCivilians||0,grade=total>=120&&lost<15?'S':total>=80?'A':total>=45?'B':'C';
  els.resultBody.innerHTML=`<div class="result-grid"><div class="result-cell"><span>CIVILIANS EVACUATED</span><b>${total}</b></div><div class="result-cell"><span>CIVILIANS LOST</span><b>${lost}</b></div><div class="result-cell"><span>ZOMBIES NEUTRALIZED</span><b>${game.kills}</b></div><div class="result-cell"><span>SAFEHOUSES / FACILITIES</span><b>${game.shelters.filter(s=>s.state==='evacuated').length} / ${game.facilitiesDone}</b></div></div><div class="small-label">OPERATION GRADE</div><div class="grade">${grade}</div>`;els.resultScreen.classList.add('visible');
}
