// V3 HUD polish for mouse aim and urgent city events.
addEventListener('pointermove',function(){const c=document.querySelector('#crosshair');if(c)c.style.opacity=(game&&game.running&&!game.paused)?'.82':'0';});
function updateHUD(){if(!game)return;
  els.civilianStat.textContent=`${game.carried} / ${game.evacuated}`;els.squadStat.textContent=`${game.soldiers.length} / ${game.squadMax}`;els.armorStat.textContent=String(1+game.vehicles.length);els.supplyStat.textContent=`K ${game.kills} · DROP ${Math.max(0,game.nextDropKills-game.kills)}`;els.formationStat.textContent=game.formation==='column'?'COLUMN':'WIDE';els.formationStat.style.color=game.formation==='column'?'var(--mint)':'var(--ice)';
  const threat=game.activeFacility?Math.min(5,2+game.facilitiesDone):Math.min(5,1+Math.floor(game.time/60));game.threat=Math.max(game.threat,threat);els.threatLabel.textContent=String(game.threat);els.threatBar.style.width=`${game.threat*20}%`;
  if(game.activeFacility){const f=game.activeFacility,t=Math.max(0,game.defenseRemaining);els.missionText.textContent=`${f.type} GARRISON · SAFE`;els.objectiveTitle.textContent=`${f.name} 주둔 방어`;els.objectiveDesc.textContent='분대는 건물 내부에서 보호받으며 강화 사격 중입니다.';els.objectiveTimer.textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.ceil(t%60)).padStart(2,'0')}`;els.objectiveTimer.classList.remove('hidden');return;}
  const urgent=(game.cityEvents||[]).find(e=>!e.done&&e.type!=='breach');if(urgent){const left=Math.max(0,urgent.expires-game.time);els.missionText.textContent=`URGENT · ${urgent.label}`;els.objectiveTitle.textContent=urgent.label;els.objectiveDesc.textContent='지도상의 긴급 신호 지점에 접근하십시오. 시간이 지나면 구조 기회를 잃습니다.';els.objectiveTimer.textContent=`00:${String(Math.ceil(left)).padStart(2,'0')}`;els.objectiveTimer.classList.remove('hidden');}
  else{els.missionText.textContent=game.facilitiesDone?`요새 거점 ${game.fortified.length} · 감염체 ${game.zombies.length}`:`도시 수색 · 감염체 ${game.zombies.length}`;const next=game.facilities.find(f=>f.state==='idle');els.objectiveTitle.textContent=next?`${next.type} 확보`:'도시 구조 작전 지속';els.objectiveDesc.textContent=next?'시설 외곽 확보 구역까지 접근해 분대를 주둔시키십시오.':'긴급 신호와 생존자, 보급 헬기 투하를 계속 확보하십시오.';els.objectiveTimer.classList.add('hidden');}
}
